spring:
  kafka:
    properties:
      #  https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-protobuf.html
      #  https://docs.confluent.io/platform/6.0.0/schema-registry/schema-validation.html#change-the-subject-naming-strategy-for-a-topic
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      derive.type: true
      specific.protobuf.value.type: com.rbiedrawa.app.proto.accounts.Account